


#ifndef Error_H_INCLUDED
#define Error_H_INCLUDED

#define REPORT_ERROR_USER_FILE_OPEN 0x00001;
#define REPORT_ERROR_USER_FILE_DELETE 0x00002;
#define REPORT_ERROR_USER_IO_SCAN 0x00003;


#define REPORT_ACTIVE_TRUE 1;
#define REPORT_ACTIVE_FALSE 0;


#define REPORT_ACTIVE_FUNCTION_END -1;



#endif